CREATE DATABASE IF NOT EXISTS magnadata_tasks;
USE magnadata_tasks;

CREATE TABLE IF NOT EXISTS Tasks (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(100) NOT NULL,
    Description VARCHAR(500),
    Status VARCHAR(20) NOT NULL DEFAULT 'Pendente',
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
